name: Handle New Issue
on: issues
jobs:
  respond_to_issue:
    runs-on: ubuntu-latest
    steps:        
      - name: Print-metadata
        run: |
          echo "Issue Title: ${{ github.event.issue.title }}"
          echo "Issue Body: ${{ github.event.issue.body }}"
          echo "${{ toJSON(github) }}"
          